server:
  port: 8080

spring:
  security:
    oauth2:
      resource-server:
        clients:
          web-client:
            origin: http://127.0.0.1:3000
        jwt:
          issuer-uri: http://127.0.0.1:9000
  data:
    redis:
      database: 0
      host: redis
      port: 6379
      password: mypass
      timeout: 60000
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false


#  r2dbc:
#    url: r2dbc:mysql://127.0.0.1:3306/mysql
#    username: root
#    password: root
#    database-platform: org.springframework.data.r2dbc.dialect.MySQLDialect
#    show-sql: true
#  datasource:
#    driver-class-name: io.r2dbc.spi.ConnectionFactory
